# Generated by Django 5.0.3 on 2024-04-12 10:37

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feeding',
            name='date_feeding',
            field=models.DateField(default=datetime.datetime(2024, 4, 12, 10, 36, 48, 633699, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='finance',
            name='date_of_operation',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 12, 10, 36, 48, 634434, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 12, 10, 36, 48, 603858, tzinfo=datetime.timezone.utc)),
        ),
    ]
