# Generated by Django 5.0.3 on 2024-04-12 10:38

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_username_alter_feeding_date_feeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='date_feeding',
            field=models.DateField(default=datetime.datetime(2024, 4, 12, 10, 38, 35, 192748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='finance',
            name='date_of_operation',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 12, 10, 38, 35, 193510, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 12, 10, 38, 35, 165629, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
